In [1]:
import numpy as np

In [9]:
arr1=np.zeros((1,3))
print(arr1)

[[0. 0. 0.]]

In [10]:
import pandas as pd

In [12]:
data = {
    "Name": ["Jaymin", "Rahul", "Amit"],
    "Age": [20, 21, 19],
    "Marks": [85, 72, 91]
}

df = pd.DataFrame(data)

print(df)

     Name  Age  Marks
0  Jaymin   20     85
1   Rahul   21     72
2    Amit   19     91

In [15]:
data1 = {
    "Name": ["Jay", "Rahul", "Amit", "Neha", "Priya", "Raj"],
    "Age": [20, 21, 19, 20, 22, 21],
    "City": ["Ahmedabad", "Surat", "Ahmedabad", "Vadodara", "Surat", "Ahmedabad"],
    "Marks": [85, 72, 91, 68, 88, 76],
    "Department": ["IT", "CE", "IT", "EC", "IT", "CE"]
}

In [17]:
df1=pd.DataFrame(data1)
print(df1)

    Name  Age       City  Marks Department
0    Jay   20  Ahmedabad     85         IT
1  Rahul   21      Surat     72         CE
2   Amit   19  Ahmedabad     91         IT
3   Neha   20   Vadodara     68         EC
4  Priya   22      Surat     88         IT
5    Raj   21  Ahmedabad     76         CE

In [19]:
df1.head()

    Name  Age       City  Marks Department
0    Jay   20  Ahmedabad     85         IT
1  Rahul   21      Surat     72         CE
2   Amit   19  Ahmedabad     91         IT
3   Neha   20   Vadodara     68         EC
4  Priya   22      Surat     88         IT

In [22]:
df1.shape

(6, 5)

In [24]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      str
 1   Age         6 non-null      int64
 2   City        6 non-null      str
 3   Marks       6 non-null      int64
 4   Department  6 non-null      str
dtypes: int64(2), str(3)
memory usage: 372.0 bytes

In [28]:
df1.describe()

             Age      Marks
count   6.000000   6.000000
mean   20.500000  80.000000
std     1.048809   9.316652
min    19.000000  68.000000
25%    20.000000  73.000000
50%    20.500000  80.500000
75%    21.000000  87.250000
max    22.000000  91.000000

In [30]:
df1[df1["Marks"]>80]

    Name  Age       City  Marks Department
0    Jay   20  Ahmedabad     85         IT
2   Amit   19  Ahmedabad     91         IT
4  Priya   22      Surat     88         IT

In [31]:
df1.sort_values("Marks")

    Name  Age       City  Marks Department
3   Neha   20   Vadodara     68         EC
1  Rahul   21      Surat     72         CE
5    Raj   21  Ahmedabad     76         CE
0    Jay   20  Ahmedabad     85         IT
4  Priya   22      Surat     88         IT
2   Amit   19  Ahmedabad     91         IT

In [32]:
data2 = {
    "Name": ["Jay", "Rahul", "Amit", "Neha"],
    "Marks": [85, None, 91, 68]
}

In [33]:
df2=pd.DataFrame(data2)
print(df2)

    Name  Marks
0    Jay   85.0
1  Rahul    NaN
2   Amit   91.0
3   Neha   68.0

In [35]:
df2.isnull()

    Name  Marks
0  False  False
1  False   True
2  False  False
3  False  False

In [36]:
df2.isnull().sum()

Name     0
Marks    1
dtype: int64

In [37]:
df2.dropna()

   Name  Marks
0   Jay   85.0
2  Amit   91.0
3  Neha   68.0

In [39]:
df2["Marks"].fillna(df2["Marks"].mean())

0    85.000000
1    81.333333
2    91.000000
3    68.000000
Name: Marks, dtype: float64

In [40]:
print(df2)

    Name  Marks
0    Jay   85.0
1  Rahul    NaN
2   Amit   91.0
3   Neha   68.0